// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4DMuz-kOOqaju_3WsUJaqC08pO9ycFs8',
    appId: '1:13888766906:web:1388d067403e41ca355383',
    messagingSenderId: '13888766906',
    projectId: 'campus-survival-4b3f6',
    authDomain: 'campus-survival-4b3f6.firebaseapp.com',
    storageBucket: 'campus-survival-4b3f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVO25bmOceiEsN38JzRnhgevRRmS7aZKg',
    appId: '1:13888766906:android:b6b9fde7928aa0f2355383',
    messagingSenderId: '13888766906',
    projectId: 'campus-survival-4b3f6',
    storageBucket: 'campus-survival-4b3f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsRPPzFBdqunuHiNtJggL5OtQD18xhy6c',
    appId: '1:13888766906:ios:319dc3b810ec0a75355383',
    messagingSenderId: '13888766906',
    projectId: 'campus-survival-4b3f6',
    storageBucket: 'campus-survival-4b3f6.firebasestorage.app',
    iosBundleId: 'com.example.campusSurvival',
  );
}
